#.travis.yml

language: java
jdk: openjdk8

branches:
  only:
    - master
    
install: true

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
  
notifications:
  email:
    recipients:
      - ghbnty0703@naver.com
